// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package controller_I3CCSR_pkg;

    localparam controller_I3CCSR_DATA_WIDTH = 32;
    localparam controller_I3CCSR_MIN_ADDR_WIDTH = 12;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__HC_CONTROL__RESUME__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__in_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__HC_CONTROL__RESUME__in_t RESUME;
        controller_I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__in_t BUS_ENABLE;
    } controller_I3CCSR__I3CBase__HC_CONTROL__in_t;

    typedef struct packed{
        logic [6:0] next;
        logic we;
    } controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__in_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__in_t DYNAMIC_ADDR;
        controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__in_t DYNAMIC_ADDR_VALID;
    } controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__in_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__in_t SOFT_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__in_t CMD_QUEUE_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__in_t RESP_QUEUE_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__in_t TX_FIFO_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__in_t RX_FIFO_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__in_t IBI_QUEUE_RST;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3CBase__PRESENT_STATE__AC_CURRENT_OWN__in_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__PRESENT_STATE__AC_CURRENT_OWN__in_t AC_CURRENT_OWN;
    } controller_I3CCSR__I3CBase__PRESENT_STATE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3CBase__INTR_STATUS__HC_INTERNAL_ERR_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3CBase__INTR_STATUS__HC_SEQ_CANCEL_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3CBase__INTR_STATUS__HC_WARN_CMD_SEQ_STALL_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3CBase__INTR_STATUS__HC_ERR_CMD_SEQ_TIMEOUT_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3CBase__INTR_STATUS__SCHED_CMD_MISSED_TICK_STAT__in_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__INTR_STATUS__HC_INTERNAL_ERR_STAT__in_t HC_INTERNAL_ERR_STAT;
        controller_I3CCSR__I3CBase__INTR_STATUS__HC_SEQ_CANCEL_STAT__in_t HC_SEQ_CANCEL_STAT;
        controller_I3CCSR__I3CBase__INTR_STATUS__HC_WARN_CMD_SEQ_STALL_STAT__in_t HC_WARN_CMD_SEQ_STALL_STAT;
        controller_I3CCSR__I3CBase__INTR_STATUS__HC_ERR_CMD_SEQ_TIMEOUT_STAT__in_t HC_ERR_CMD_SEQ_TIMEOUT_STAT;
        controller_I3CCSR__I3CBase__INTR_STATUS__SCHED_CMD_MISSED_TICK_STAT__in_t SCHED_CMD_MISSED_TICK_STAT;
    } controller_I3CCSR__I3CBase__INTR_STATUS__in_t;

    typedef struct packed{
        logic [4:0] next;
        logic we;
    } controller_I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__in_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__in_t TABLE_INDEX;
    } controller_I3CCSR__I3CBase__DCT_SECTION_OFFSET__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__in_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__in_t IBI_DATA_ABORT_MON;
    } controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__in_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__HC_CONTROL__in_t HC_CONTROL;
        controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__in_t CONTROLLER_DEVICE_ADDR;
        controller_I3CCSR__I3CBase__RESET_CONTROL__in_t RESET_CONTROL;
        controller_I3CCSR__I3CBase__PRESENT_STATE__in_t PRESENT_STATE;
        controller_I3CCSR__I3CBase__INTR_STATUS__in_t INTR_STATUS;
        controller_I3CCSR__I3CBase__DCT_SECTION_OFFSET__in_t DCT_SECTION_OFFSET;
        controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__in_t IBI_DATA_ABORT_CTRL;
    } controller_I3CCSR__I3CBase__in_t;

    typedef struct packed{
        logic wr_ack;
    } controller_I3CCSR__PIOControl__COMMAND_PORT__in_t;

    typedef struct packed {
        logic [31:0] RESPONSE_DATA;
    } controller_I3CCSR__PIOControl__RESPONSE_PORT__fields__in_t;

    typedef struct packed{
        logic rd_ack;
        controller_I3CCSR__PIOControl__RESPONSE_PORT__fields__in_t rd_data;
    } controller_I3CCSR__PIOControl__RESPONSE_PORT__in_t;

    typedef struct packed{
        logic wr_ack;
    } controller_I3CCSR__PIOControl__TX_DATA_PORT__in_t;

    typedef struct packed {
        logic [31:0] RX_DATA;
    } controller_I3CCSR__PIOControl__RX_DATA_PORT__fields__in_t;

    typedef struct packed{
        logic rd_ack;
        controller_I3CCSR__PIOControl__RX_DATA_PORT__fields__in_t rd_data;
    } controller_I3CCSR__PIOControl__RX_DATA_PORT__in_t;

    typedef struct packed {
        logic [31:0] IBI_DATA;
    } controller_I3CCSR__PIOControl__IBI_PORT__fields__in_t;

    typedef struct packed{
        logic rd_ack;
        controller_I3CCSR__PIOControl__IBI_PORT__fields__in_t rd_data;
    } controller_I3CCSR__PIOControl__IBI_PORT__in_t;

    typedef struct packed{
        logic [7:0] next;
        logic we;
    } controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__CMD_EMPTY_BUF_THLD__in_t;

    typedef struct packed{
        logic [7:0] next;
        logic we;
    } controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__RESP_BUF_THLD__in_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__CMD_EMPTY_BUF_THLD__in_t CMD_EMPTY_BUF_THLD;
        controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__RESP_BUF_THLD__in_t RESP_BUF_THLD;
    } controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__TX_THLD_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__RX_THLD_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__IBI_STATUS_THLD_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__CMD_QUEUE_READY_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__RESP_READY_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ABORT_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ERR_STAT__in_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__TX_THLD_STAT__in_t TX_THLD_STAT;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__RX_THLD_STAT__in_t RX_THLD_STAT;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__IBI_STATUS_THLD_STAT__in_t IBI_STATUS_THLD_STAT;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__CMD_QUEUE_READY_STAT__in_t CMD_QUEUE_READY_STAT;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__RESP_READY_STAT__in_t RESP_READY_STAT;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ABORT_STAT__in_t TRANSFER_ABORT_STAT;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ERR_STAT__in_t TRANSFER_ERR_STAT;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__in_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__COMMAND_PORT__in_t COMMAND_PORT;
        controller_I3CCSR__PIOControl__RESPONSE_PORT__in_t RESPONSE_PORT;
        controller_I3CCSR__PIOControl__TX_DATA_PORT__in_t TX_DATA_PORT;
        controller_I3CCSR__PIOControl__RX_DATA_PORT__in_t RX_DATA_PORT;
        controller_I3CCSR__PIOControl__IBI_PORT__in_t IBI_PORT;
        controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__in_t QUEUE_THLD_CTRL;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__in_t PIO_INTR_STATUS;
    } controller_I3CCSR__PIOControl__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__PENDING_RX_NACK__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__HANDOFF_DELAY_NACK__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__ACR_FSM_OP_SELECT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__PRIME_ACCEPT_GETACCCR__in_t;

    typedef struct packed{
        logic next;
        logic we;
        logic hwclr;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__HANDOFF_DEEP_SLEEP__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__TARGET_XACT_ENABLE__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_SETAASA_ENABLE__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_SETDASA_ENABLE__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_ENTDAA_ENABLE__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__PENDING_RX_NACK__in_t PENDING_RX_NACK;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__HANDOFF_DELAY_NACK__in_t HANDOFF_DELAY_NACK;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__ACR_FSM_OP_SELECT__in_t ACR_FSM_OP_SELECT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__PRIME_ACCEPT_GETACCCR__in_t PRIME_ACCEPT_GETACCCR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__HANDOFF_DEEP_SLEEP__in_t HANDOFF_DEEP_SLEEP;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__TARGET_XACT_ENABLE__in_t TARGET_XACT_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_SETAASA_ENABLE__in_t DAA_SETAASA_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_SETDASA_ENABLE__in_t DAA_SETDASA_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_ENTDAA_ENABLE__in_t DAA_ENTDAA_ENABLE;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__in_t;

    typedef struct packed{
        logic [6:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__STATIC_ADDR__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__STATIC_ADDR_VALID__in_t;

    typedef struct packed{
        logic [6:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__DYNAMIC_ADDR__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__DYNAMIC_ADDR_VALID__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__STATIC_ADDR__in_t STATIC_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__STATIC_ADDR_VALID__in_t STATIC_ADDR_VALID;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__DYNAMIC_ADDR__in_t DYNAMIC_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__DYNAMIC_ADDR_VALID__in_t DYNAMIC_ADDR_VALID;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__AC_CURRENT_OWN__in_t;

    typedef struct packed{
        logic [2:0] next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__SIMPLE_CRR_STATUS__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__HJ_REQ_STATUS__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__AC_CURRENT_OWN__in_t AC_CURRENT_OWN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__SIMPLE_CRR_STATUS__in_t SIMPLE_CRR_STATUS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__HJ_REQ_STATUS__in_t HJ_REQ_STATUS;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_OK_REMAIN_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_OK_PRIMED_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_ERR_FAIL_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_ERR_M3_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CRR_RESPONSE_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_DYN_ADDR_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_NACKED_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_OK_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_ERR_STAT__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_OP_RSTACT_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_PARAM_MODIFIED_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_UNHANDLED_NACK_STAT__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_FATAL_RSTDAA_ERR_STAT__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_OK_REMAIN_STAT__in_t ACR_HANDOFF_OK_REMAIN_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_OK_PRIMED_STAT__in_t ACR_HANDOFF_OK_PRIMED_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_ERR_FAIL_STAT__in_t ACR_HANDOFF_ERR_FAIL_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_ERR_M3_STAT__in_t ACR_HANDOFF_ERR_M3_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CRR_RESPONSE_STAT__in_t CRR_RESPONSE_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_DYN_ADDR_STAT__in_t STBY_CR_DYN_ADDR_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_NACKED_STAT__in_t STBY_CR_ACCEPT_NACKED_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_OK_STAT__in_t STBY_CR_ACCEPT_OK_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_ERR_STAT__in_t STBY_CR_ACCEPT_ERR_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_OP_RSTACT_STAT__in_t STBY_CR_OP_RSTACT_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_PARAM_MODIFIED_STAT__in_t CCC_PARAM_MODIFIED_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_UNHANDLED_NACK_STAT__in_t CCC_UNHANDLED_NACK_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_FATAL_RSTDAA_ERR_STAT__in_t CCC_FATAL_RSTDAA_ERR_STAT;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_OK_REMAIN_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_OK_PRIMED_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_ERR_FAIL_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_ERR_M3_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CRR_RESPONSE_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_DYN_ADDR_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_NACKED_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_OK_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_ERR_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_OP_RSTACT_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_PARAM_MODIFIED_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_UNHANDLED_NACK_SIGNAL_EN__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_FATAL_RSTDAA_ERR_SIGNAL_EN__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_OK_REMAIN_SIGNAL_EN__in_t ACR_HANDOFF_OK_REMAIN_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_OK_PRIMED_SIGNAL_EN__in_t ACR_HANDOFF_OK_PRIMED_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_ERR_FAIL_SIGNAL_EN__in_t ACR_HANDOFF_ERR_FAIL_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_ERR_M3_SIGNAL_EN__in_t ACR_HANDOFF_ERR_M3_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CRR_RESPONSE_SIGNAL_EN__in_t CRR_RESPONSE_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_DYN_ADDR_SIGNAL_EN__in_t STBY_CR_DYN_ADDR_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_NACKED_SIGNAL_EN__in_t STBY_CR_ACCEPT_NACKED_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_OK_SIGNAL_EN__in_t STBY_CR_ACCEPT_OK_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_ERR_SIGNAL_EN__in_t STBY_CR_ACCEPT_ERR_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_OP_RSTACT_SIGNAL_EN__in_t STBY_CR_OP_RSTACT_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_PARAM_MODIFIED_SIGNAL_EN__in_t CCC_PARAM_MODIFIED_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_UNHANDLED_NACK_SIGNAL_EN__in_t CCC_UNHANDLED_NACK_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_FATAL_RSTDAA_ERR_SIGNAL_EN__in_t CCC_FATAL_RSTDAA_ERR_SIGNAL_EN;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CRR_RESPONSE_FORCE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_DYN_ADDR_FORCE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_NACKED_FORCE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_OK_FORCE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_ERR_FORCE__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_OP_RSTACT_FORCE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_PARAM_MODIFIED_FORCE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_UNHANDLED_NACK_FORCE__in_t;

    typedef struct packed{
        logic next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_FATAL_RSTDAA_ERR_FORCE__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CRR_RESPONSE_FORCE__in_t CRR_RESPONSE_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_DYN_ADDR_FORCE__in_t STBY_CR_DYN_ADDR_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_NACKED_FORCE__in_t STBY_CR_ACCEPT_NACKED_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_OK_FORCE__in_t STBY_CR_ACCEPT_OK_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_ERR_FORCE__in_t STBY_CR_ACCEPT_ERR_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_OP_RSTACT_FORCE__in_t STBY_CR_OP_RSTACT_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_PARAM_MODIFIED_FORCE__in_t CCC_PARAM_MODIFIED_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_UNHANDLED_NACK_FORCE__in_t CCC_UNHANDLED_NACK_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_FATAL_RSTDAA_ERR_FORCE__in_t CCC_FATAL_RSTDAA_ERR_FORCE;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__in_t;

    typedef struct packed{
        logic [2:0] next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__F2_CRCAP1_BUS_CONFIG__in_t;

    typedef struct packed{
        logic [3:0] next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__F2_CRCAP2_DEV_INTERACT__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__F2_CRCAP1_BUS_CONFIG__in_t F2_CRCAP1_BUS_CONFIG;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__F2_CRCAP2_DEV_INTERACT__in_t F2_CRCAP2_DEV_INTERACT;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__in_t;

    typedef struct packed{
        logic [7:0] next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RST_ACTION__in_t;

    typedef struct packed{
        logic [7:0] next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_TIME_PERIPHERAL__in_t;

    typedef struct packed{
        logic [7:0] next;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_TIME_TARGET__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_DYNAMIC_ADDR__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RST_ACTION__in_t RST_ACTION;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_TIME_PERIPHERAL__in_t RESET_TIME_PERIPHERAL;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_TIME_TARGET__in_t RESET_TIME_TARGET;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_DYNAMIC_ADDR__in_t RESET_DYNAMIC_ADDR;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__in_t;

    typedef struct packed{
        logic [6:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_STATIC_ADDR__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_STATIC_ADDR_VALID__in_t;

    typedef struct packed{
        logic [6:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_DYNAMIC_ADDR__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_DYNAMIC_ADDR_VALID__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_STATIC_ADDR__in_t VIRT_STATIC_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_STATIC_ADDR_VALID__in_t VIRT_STATIC_ADDR_VALID;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_DYNAMIC_ADDR__in_t VIRT_DYNAMIC_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_DYNAMIC_ADDR_VALID__in_t VIRT_DYNAMIC_ADDR_VALID;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__in_t;

    typedef struct packed{
        logic [15:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MWL__MWL__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MWL__MWL__in_t MWL;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MWL__in_t;

    typedef struct packed{
        logic [15:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__MRL__in_t;

    typedef struct packed{
        logic [7:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__IBIL__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__MRL__in_t MRL;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__IBIL__in_t IBIL;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__in_t;

    typedef struct packed{
        logic lock_id_csrs_hw_sig;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__in_t STBY_CR_CONTROL;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__in_t STBY_CR_DEVICE_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__in_t STBY_CR_STATUS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__in_t STBY_CR_INTR_STATUS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__in_t STBY_CR_INTR_SIGNAL_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__in_t STBY_CR_INTR_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__in_t STBY_CR_CCC_CONFIG_GETCAPS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__in_t STBY_CR_CCC_CONFIG_RSTACT_PARAMS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__in_t STBY_CR_VIRT_DEVICE_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MWL__in_t STBY_CR_MWL;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__in_t STBY_CR_MRL;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__in_t;

    typedef struct packed{
        logic next;
        logic we;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__REC_PAYLOAD_DONE__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__REC_PAYLOAD_DONE__in_t REC_PAYLOAD_DONE;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__in_t;

    typedef struct packed{
        logic [7:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__DEVICE_RESET_CTRL__in_t;

    typedef struct packed{
        logic [7:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__RECOVERY_CTRL_ACTIVATE_REC_IMG__in_t;

    typedef struct packed{
        logic [7:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__INDIRECT_FIFO_CTRL_RESET__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__DEVICE_RESET_CTRL__in_t DEVICE_RESET_CTRL;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__RECOVERY_CTRL_ACTIVATE_REC_IMG__in_t RECOVERY_CTRL_ACTIVATE_REC_IMG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__INDIRECT_FIFO_CTRL_RESET__in_t INDIRECT_FIFO_CTRL_RESET;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__in_t REC_INTF_CFG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__in_t REC_INTF_REG_W1C_ACCESS;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__in_t;

    typedef struct packed{
        logic [1:0] next;
        logic we;
    } controller_I3CCSR__I3C_EC__CtrlCfg__CONTROLLER_CONFIG__OPERATION_MODE__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__CtrlCfg__CONTROLLER_CONFIG__OPERATION_MODE__in_t OPERATION_MODE;
    } controller_I3CCSR__I3C_EC__CtrlCfg__CONTROLLER_CONFIG__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__CtrlCfg__CONTROLLER_CONFIG__in_t CONTROLLER_CONFIG;
    } controller_I3CCSR__I3C_EC__CtrlCfg__in_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__in_t StdbyCtrlMode;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__in_t SoCMgmtIf;
        controller_I3CCSR__I3C_EC__CtrlCfg__in_t CtrlCfg;
    } controller_I3CCSR__I3C_EC__in_t;

    typedef struct packed{
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } controller_I3CCSR__DAT__in_t;

    typedef struct packed{
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } controller_I3CCSR__DCT__in_t;

    typedef struct packed{
        logic rst_ni;
        controller_I3CCSR__I3CBase__in_t I3CBase;
        controller_I3CCSR__PIOControl__in_t PIOControl;
        controller_I3CCSR__I3C_EC__in_t I3C_EC;
        controller_I3CCSR__DAT__in_t DAT;
        controller_I3CCSR__DCT__in_t DCT;
    } controller_I3CCSR__in_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__HC_CONTROL__IBA_INCLUDE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__HC_CONTROL__I2C_DEV_PRESENT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__HC_CONTROL__HOT_JOIN_CTRL__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__HC_CONTROL__HALT_ON_CMD_SEQ_TIMEOUT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__HC_CONTROL__ABORT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__HC_CONTROL__RESUME__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__HC_CONTROL__IBA_INCLUDE__out_t IBA_INCLUDE;
        controller_I3CCSR__I3CBase__HC_CONTROL__I2C_DEV_PRESENT__out_t I2C_DEV_PRESENT;
        controller_I3CCSR__I3CBase__HC_CONTROL__HOT_JOIN_CTRL__out_t HOT_JOIN_CTRL;
        controller_I3CCSR__I3CBase__HC_CONTROL__HALT_ON_CMD_SEQ_TIMEOUT__out_t HALT_ON_CMD_SEQ_TIMEOUT;
        controller_I3CCSR__I3CBase__HC_CONTROL__ABORT__out_t ABORT;
        controller_I3CCSR__I3CBase__HC_CONTROL__RESUME__out_t RESUME;
        controller_I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__out_t BUS_ENABLE;
    } controller_I3CCSR__I3CBase__HC_CONTROL__out_t;

    typedef struct packed{
        logic [6:0] value;
    } controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__out_t DYNAMIC_ADDR;
        controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__out_t DYNAMIC_ADDR_VALID;
    } controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__out_t SOFT_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__out_t CMD_QUEUE_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__out_t RESP_QUEUE_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__out_t TX_FIFO_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__out_t RX_FIFO_RST;
        controller_I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__out_t IBI_QUEUE_RST;
    } controller_I3CCSR__I3CBase__RESET_CONTROL__out_t;

    typedef struct packed{
        logic intr;
    } controller_I3CCSR__I3CBase__INTR_STATUS__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_INTERNAL_ERR_STAT_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_SEQ_CANCEL_STAT_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_WARN_CMD_SEQ_STALL_STAT_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__SCHED_CMD_MISSED_TICK_STAT_EN__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_INTERNAL_ERR_STAT_EN__out_t HC_INTERNAL_ERR_STAT_EN;
        controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_SEQ_CANCEL_STAT_EN__out_t HC_SEQ_CANCEL_STAT_EN;
        controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_WARN_CMD_SEQ_STALL_STAT_EN__out_t HC_WARN_CMD_SEQ_STALL_STAT_EN;
        controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN__out_t HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN;
        controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__SCHED_CMD_MISSED_TICK_STAT_EN__out_t SCHED_CMD_MISSED_TICK_STAT_EN;
    } controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_INTERNAL_ERR_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_SEQ_CANCEL_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_WARN_CMD_SEQ_STALL_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__SCHED_CMD_MISSED_TICK_SIGNAL_EN__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_INTERNAL_ERR_SIGNAL_EN__out_t HC_INTERNAL_ERR_SIGNAL_EN;
        controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_SEQ_CANCEL_SIGNAL_EN__out_t HC_SEQ_CANCEL_SIGNAL_EN;
        controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_WARN_CMD_SEQ_STALL_SIGNAL_EN__out_t HC_WARN_CMD_SEQ_STALL_SIGNAL_EN;
        controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN__out_t HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN;
        controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__SCHED_CMD_MISSED_TICK_SIGNAL_EN__out_t SCHED_CMD_MISSED_TICK_SIGNAL_EN;
    } controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_FORCE__HC_INTERNAL_ERR_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_FORCE__HC_SEQ_CANCEL_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_FORCE__HC_WARN_CMD_SEQ_STALL_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_FORCE__HC_ERR_CMD_SEQ_TIMEOUT_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__INTR_FORCE__SCHED_CMD_MISSED_TICK_FORCE__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__INTR_FORCE__HC_INTERNAL_ERR_FORCE__out_t HC_INTERNAL_ERR_FORCE;
        controller_I3CCSR__I3CBase__INTR_FORCE__HC_SEQ_CANCEL_FORCE__out_t HC_SEQ_CANCEL_FORCE;
        controller_I3CCSR__I3CBase__INTR_FORCE__HC_WARN_CMD_SEQ_STALL_FORCE__out_t HC_WARN_CMD_SEQ_STALL_FORCE;
        controller_I3CCSR__I3CBase__INTR_FORCE__HC_ERR_CMD_SEQ_TIMEOUT_FORCE__out_t HC_ERR_CMD_SEQ_TIMEOUT_FORCE;
        controller_I3CCSR__I3CBase__INTR_FORCE__SCHED_CMD_MISSED_TICK_FORCE__out_t SCHED_CMD_MISSED_TICK_FORCE;
    } controller_I3CCSR__I3CBase__INTR_FORCE__out_t;

    typedef struct packed{
        logic [4:0] value;
    } controller_I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__out_t TABLE_INDEX;
    } controller_I3CCSR__I3CBase__DCT_SECTION_OFFSET__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_HJ_REJECTED__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_CRR_REJECTED__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_IBI_REJECTED__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_HJ_REJECTED__out_t NOTIFY_HJ_REJECTED;
        controller_I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_CRR_REJECTED__out_t NOTIFY_CRR_REJECTED;
        controller_I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_IBI_REJECTED__out_t NOTIFY_IBI_REJECTED;
    } controller_I3CCSR__I3CBase__IBI_NOTIFY_CTRL__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_IBI_ID__out_t;

    typedef struct packed{
        logic [1:0] value;
    } controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__AFTER_N_CHUNKS__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_STATUS_TYPE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_IBI_ID__out_t MATCH_IBI_ID;
        controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__AFTER_N_CHUNKS__out_t AFTER_N_CHUNKS;
        controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_STATUS_TYPE__out_t MATCH_STATUS_TYPE;
        controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__out_t IBI_DATA_ABORT_MON;
    } controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__DEV_CTX_BASE_LO__BASE_LO__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__DEV_CTX_BASE_LO__BASE_LO__out_t BASE_LO;
    } controller_I3CCSR__I3CBase__DEV_CTX_BASE_LO__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3CBase__DEV_CTX_BASE_HI__BASE_HI__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__DEV_CTX_BASE_HI__BASE_HI__out_t BASE_HI;
    } controller_I3CCSR__I3CBase__DEV_CTX_BASE_HI__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__HC_CONTROL__out_t HC_CONTROL;
        controller_I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__out_t CONTROLLER_DEVICE_ADDR;
        controller_I3CCSR__I3CBase__RESET_CONTROL__out_t RESET_CONTROL;
        controller_I3CCSR__I3CBase__INTR_STATUS__out_t INTR_STATUS;
        controller_I3CCSR__I3CBase__INTR_STATUS_ENABLE__out_t INTR_STATUS_ENABLE;
        controller_I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__out_t INTR_SIGNAL_ENABLE;
        controller_I3CCSR__I3CBase__INTR_FORCE__out_t INTR_FORCE;
        controller_I3CCSR__I3CBase__DCT_SECTION_OFFSET__out_t DCT_SECTION_OFFSET;
        controller_I3CCSR__I3CBase__IBI_NOTIFY_CTRL__out_t IBI_NOTIFY_CTRL;
        controller_I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__out_t IBI_DATA_ABORT_CTRL;
        controller_I3CCSR__I3CBase__DEV_CTX_BASE_LO__out_t DEV_CTX_BASE_LO;
        controller_I3CCSR__I3CBase__DEV_CTX_BASE_HI__out_t DEV_CTX_BASE_HI;
    } controller_I3CCSR__I3CBase__out_t;

    typedef struct packed {
        logic [31:0] COMMAND_DATA;
    } controller_I3CCSR__PIOControl__COMMAND_PORT__fields__out_t;

    typedef struct packed{
        logic req;
        logic req_is_wr;
        controller_I3CCSR__PIOControl__COMMAND_PORT__fields__out_t wr_data;
        controller_I3CCSR__PIOControl__COMMAND_PORT__fields__out_t wr_biten;
    } controller_I3CCSR__PIOControl__COMMAND_PORT__out_t;

    typedef struct packed{
        logic req;
        logic req_is_wr;
    } controller_I3CCSR__PIOControl__RESPONSE_PORT__out_t;

    typedef struct packed {
        logic [31:0] TX_DATA;
    } controller_I3CCSR__PIOControl__TX_DATA_PORT__fields__out_t;

    typedef struct packed{
        logic req;
        logic req_is_wr;
        controller_I3CCSR__PIOControl__TX_DATA_PORT__fields__out_t wr_data;
        controller_I3CCSR__PIOControl__TX_DATA_PORT__fields__out_t wr_biten;
    } controller_I3CCSR__PIOControl__TX_DATA_PORT__out_t;

    typedef struct packed{
        logic req;
        logic req_is_wr;
    } controller_I3CCSR__PIOControl__RX_DATA_PORT__out_t;

    typedef struct packed{
        logic req;
        logic req_is_wr;
    } controller_I3CCSR__PIOControl__IBI_PORT__out_t;

    typedef struct packed{
        logic [7:0] value;
        logic swmod;
    } controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__CMD_EMPTY_BUF_THLD__out_t;

    typedef struct packed{
        logic [7:0] value;
        logic swmod;
    } controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__RESP_BUF_THLD__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_DATA_SEGMENT_SIZE__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_STATUS_THLD__out_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__CMD_EMPTY_BUF_THLD__out_t CMD_EMPTY_BUF_THLD;
        controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__RESP_BUF_THLD__out_t RESP_BUF_THLD;
        controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_DATA_SEGMENT_SIZE__out_t IBI_DATA_SEGMENT_SIZE;
        controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_STATUS_THLD__out_t IBI_STATUS_THLD;
    } controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_BUF_THLD__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_BUF_THLD__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_START_THLD__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_START_THLD__out_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_BUF_THLD__out_t TX_BUF_THLD;
        controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_BUF_THLD__out_t RX_BUF_THLD;
        controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_START_THLD__out_t TX_START_THLD;
        controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_START_THLD__out_t RX_START_THLD;
    } controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__out_t;

    typedef struct packed{
        logic intr;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS_ENABLE__TRANSFER_ABORT_STAT_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS_ENABLE__TRANSFER_ERR_STAT_EN__out_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS_ENABLE__TRANSFER_ABORT_STAT_EN__out_t TRANSFER_ABORT_STAT_EN;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS_ENABLE__TRANSFER_ERR_STAT_EN__out_t TRANSFER_ERR_STAT_EN;
    } controller_I3CCSR__PIOControl__PIO_INTR_STATUS_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_FORCE__TX_THLD_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_FORCE__RX_THLD_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_FORCE__IBI_THLD_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_FORCE__CMD_QUEUE_READY_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_FORCE__RESP_READY_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ABORT_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ERR_FORCE__out_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__PIO_INTR_FORCE__TX_THLD_FORCE__out_t TX_THLD_FORCE;
        controller_I3CCSR__PIOControl__PIO_INTR_FORCE__RX_THLD_FORCE__out_t RX_THLD_FORCE;
        controller_I3CCSR__PIOControl__PIO_INTR_FORCE__IBI_THLD_FORCE__out_t IBI_THLD_FORCE;
        controller_I3CCSR__PIOControl__PIO_INTR_FORCE__CMD_QUEUE_READY_FORCE__out_t CMD_QUEUE_READY_FORCE;
        controller_I3CCSR__PIOControl__PIO_INTR_FORCE__RESP_READY_FORCE__out_t RESP_READY_FORCE;
        controller_I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ABORT_FORCE__out_t TRANSFER_ABORT_FORCE;
        controller_I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ERR_FORCE__out_t TRANSFER_ERR_FORCE;
    } controller_I3CCSR__PIOControl__PIO_INTR_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_CONTROL__ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_CONTROL__RS__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__PIOControl__PIO_CONTROL__ABORT__out_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__PIO_CONTROL__ENABLE__out_t ENABLE;
        controller_I3CCSR__PIOControl__PIO_CONTROL__RS__out_t RS;
        controller_I3CCSR__PIOControl__PIO_CONTROL__ABORT__out_t ABORT;
    } controller_I3CCSR__PIOControl__PIO_CONTROL__out_t;

    typedef struct packed{
        controller_I3CCSR__PIOControl__COMMAND_PORT__out_t COMMAND_PORT;
        controller_I3CCSR__PIOControl__RESPONSE_PORT__out_t RESPONSE_PORT;
        controller_I3CCSR__PIOControl__TX_DATA_PORT__out_t TX_DATA_PORT;
        controller_I3CCSR__PIOControl__RX_DATA_PORT__out_t RX_DATA_PORT;
        controller_I3CCSR__PIOControl__IBI_PORT__out_t IBI_PORT;
        controller_I3CCSR__PIOControl__QUEUE_THLD_CTRL__out_t QUEUE_THLD_CTRL;
        controller_I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__out_t DATA_BUFFER_THLD_CTRL;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS__out_t PIO_INTR_STATUS;
        controller_I3CCSR__PIOControl__PIO_INTR_STATUS_ENABLE__out_t PIO_INTR_STATUS_ENABLE;
        controller_I3CCSR__PIOControl__PIO_INTR_FORCE__out_t PIO_INTR_FORCE;
        controller_I3CCSR__PIOControl__PIO_CONTROL__out_t PIO_CONTROL;
    } controller_I3CCSR__PIOControl__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__EXTCAP_HEADER__CAP_ID__out_t;

    typedef struct packed{
        logic [15:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__EXTCAP_HEADER__CAP_LENGTH__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__EXTCAP_HEADER__CAP_ID__out_t CAP_ID;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__EXTCAP_HEADER__CAP_LENGTH__out_t CAP_LENGTH;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__EXTCAP_HEADER__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__PENDING_RX_NACK__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__HANDOFF_DELAY_NACK__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__ACR_FSM_OP_SELECT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__PRIME_ACCEPT_GETACCCR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__HANDOFF_DEEP_SLEEP__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__CR_REQUEST_SEND__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__BAST_CCC_IBI_RING__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__TARGET_XACT_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_SETAASA_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_SETDASA_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_ENTDAA_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__RSTACT_DEFBYTE_02__out_t;

    typedef struct packed{
        logic [1:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__STBY_CR_ENABLE_INIT__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__PENDING_RX_NACK__out_t PENDING_RX_NACK;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__HANDOFF_DELAY_NACK__out_t HANDOFF_DELAY_NACK;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__ACR_FSM_OP_SELECT__out_t ACR_FSM_OP_SELECT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__PRIME_ACCEPT_GETACCCR__out_t PRIME_ACCEPT_GETACCCR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__HANDOFF_DEEP_SLEEP__out_t HANDOFF_DEEP_SLEEP;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__CR_REQUEST_SEND__out_t CR_REQUEST_SEND;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__BAST_CCC_IBI_RING__out_t BAST_CCC_IBI_RING;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__TARGET_XACT_ENABLE__out_t TARGET_XACT_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_SETAASA_ENABLE__out_t DAA_SETAASA_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_SETDASA_ENABLE__out_t DAA_SETDASA_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__DAA_ENTDAA_ENABLE__out_t DAA_ENTDAA_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__RSTACT_DEFBYTE_02__out_t RSTACT_DEFBYTE_02;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__STBY_CR_ENABLE_INIT__out_t STBY_CR_ENABLE_INIT;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__out_t;

    typedef struct packed{
        logic [6:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__STATIC_ADDR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__STATIC_ADDR_VALID__out_t;

    typedef struct packed{
        logic [6:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__DYNAMIC_ADDR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__DYNAMIC_ADDR_VALID__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__STATIC_ADDR__out_t STATIC_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__STATIC_ADDR_VALID__out_t STATIC_ADDR_VALID;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__DYNAMIC_ADDR__out_t DYNAMIC_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__DYNAMIC_ADDR_VALID__out_t DYNAMIC_ADDR_VALID;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__SIMPLE_CRR_SUPPORT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__TARGET_XACT_SUPPORT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__DAA_SETAASA_SUPPORT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__DAA_SETDASA_SUPPORT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__DAA_ENTDAA_SUPPORT__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__SIMPLE_CRR_SUPPORT__out_t SIMPLE_CRR_SUPPORT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__TARGET_XACT_SUPPORT__out_t TARGET_XACT_SUPPORT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__DAA_SETAASA_SUPPORT__out_t DAA_SETAASA_SUPPORT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__DAA_SETDASA_SUPPORT__out_t DAA_SETDASA_SUPPORT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__DAA_ENTDAA_SUPPORT__out_t DAA_ENTDAA_SUPPORT;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__out_t;

    typedef struct packed{
        logic [14:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__PID_HI__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__DCR__out_t;

    typedef struct packed{
        logic [4:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__BCR_VAR__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__BCR_FIXED__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__PID_HI__out_t PID_HI;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__DCR__out_t DCR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__BCR_VAR__out_t BCR_VAR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__BCR_FIXED__out_t BCR_FIXED;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__AC_CURRENT_OWN__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__SIMPLE_CRR_STATUS__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__HJ_REQ_STATUS__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__AC_CURRENT_OWN__out_t AC_CURRENT_OWN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__SIMPLE_CRR_STATUS__out_t SIMPLE_CRR_STATUS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__HJ_REQ_STATUS__out_t HJ_REQ_STATUS;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__out_t;

    typedef struct packed{
        logic [14:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__PID_HI__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__DCR__out_t;

    typedef struct packed{
        logic [4:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__BCR_VAR__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__BCR_FIXED__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__PID_HI__out_t PID_HI;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__DCR__out_t DCR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__BCR_VAR__out_t BCR_VAR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__BCR_FIXED__out_t BCR_FIXED;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_PID_LO__PID_LO__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_PID_LO__PID_LO__out_t PID_LO;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_PID_LO__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_OK_REMAIN_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_OK_PRIMED_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_ERR_FAIL_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_ERR_M3_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CRR_RESPONSE_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_DYN_ADDR_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_NACKED_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_OK_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_ERR_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_OP_RSTACT_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_PARAM_MODIFIED_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_UNHANDLED_NACK_STAT__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_FATAL_RSTDAA_ERR_STAT__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_OK_REMAIN_STAT__out_t ACR_HANDOFF_OK_REMAIN_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_OK_PRIMED_STAT__out_t ACR_HANDOFF_OK_PRIMED_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_ERR_FAIL_STAT__out_t ACR_HANDOFF_ERR_FAIL_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__ACR_HANDOFF_ERR_M3_STAT__out_t ACR_HANDOFF_ERR_M3_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CRR_RESPONSE_STAT__out_t CRR_RESPONSE_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_DYN_ADDR_STAT__out_t STBY_CR_DYN_ADDR_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_NACKED_STAT__out_t STBY_CR_ACCEPT_NACKED_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_OK_STAT__out_t STBY_CR_ACCEPT_OK_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_ACCEPT_ERR_STAT__out_t STBY_CR_ACCEPT_ERR_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__STBY_CR_OP_RSTACT_STAT__out_t STBY_CR_OP_RSTACT_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_PARAM_MODIFIED_STAT__out_t CCC_PARAM_MODIFIED_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_UNHANDLED_NACK_STAT__out_t CCC_UNHANDLED_NACK_STAT;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__CCC_FATAL_RSTDAA_ERR_STAT__out_t CCC_FATAL_RSTDAA_ERR_STAT;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_PID_LO__PID_LO__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_PID_LO__PID_LO__out_t PID_LO;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_PID_LO__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_OK_REMAIN_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_OK_PRIMED_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_ERR_FAIL_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_ERR_M3_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CRR_RESPONSE_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_DYN_ADDR_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_NACKED_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_OK_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_ERR_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_OP_RSTACT_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_PARAM_MODIFIED_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_UNHANDLED_NACK_SIGNAL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_FATAL_RSTDAA_ERR_SIGNAL_EN__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_OK_REMAIN_SIGNAL_EN__out_t ACR_HANDOFF_OK_REMAIN_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_OK_PRIMED_SIGNAL_EN__out_t ACR_HANDOFF_OK_PRIMED_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_ERR_FAIL_SIGNAL_EN__out_t ACR_HANDOFF_ERR_FAIL_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__ACR_HANDOFF_ERR_M3_SIGNAL_EN__out_t ACR_HANDOFF_ERR_M3_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CRR_RESPONSE_SIGNAL_EN__out_t CRR_RESPONSE_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_DYN_ADDR_SIGNAL_EN__out_t STBY_CR_DYN_ADDR_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_NACKED_SIGNAL_EN__out_t STBY_CR_ACCEPT_NACKED_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_OK_SIGNAL_EN__out_t STBY_CR_ACCEPT_OK_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_ACCEPT_ERR_SIGNAL_EN__out_t STBY_CR_ACCEPT_ERR_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__STBY_CR_OP_RSTACT_SIGNAL_EN__out_t STBY_CR_OP_RSTACT_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_PARAM_MODIFIED_SIGNAL_EN__out_t CCC_PARAM_MODIFIED_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_UNHANDLED_NACK_SIGNAL_EN__out_t CCC_UNHANDLED_NACK_SIGNAL_EN;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__CCC_FATAL_RSTDAA_ERR_SIGNAL_EN__out_t CCC_FATAL_RSTDAA_ERR_SIGNAL_EN;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CRR_RESPONSE_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_DYN_ADDR_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_NACKED_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_OK_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_ERR_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_OP_RSTACT_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_PARAM_MODIFIED_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_UNHANDLED_NACK_FORCE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_FATAL_RSTDAA_ERR_FORCE__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CRR_RESPONSE_FORCE__out_t CRR_RESPONSE_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_DYN_ADDR_FORCE__out_t STBY_CR_DYN_ADDR_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_NACKED_FORCE__out_t STBY_CR_ACCEPT_NACKED_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_OK_FORCE__out_t STBY_CR_ACCEPT_OK_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_ACCEPT_ERR_FORCE__out_t STBY_CR_ACCEPT_ERR_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__STBY_CR_OP_RSTACT_FORCE__out_t STBY_CR_OP_RSTACT_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_PARAM_MODIFIED_FORCE__out_t CCC_PARAM_MODIFIED_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_UNHANDLED_NACK_FORCE__out_t CCC_UNHANDLED_NACK_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__CCC_FATAL_RSTDAA_ERR_FORCE__out_t CCC_FATAL_RSTDAA_ERR_FORCE;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__out_t;

    typedef struct packed{
        logic [2:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__F2_CRCAP1_BUS_CONFIG__out_t;

    typedef struct packed{
        logic [3:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__F2_CRCAP2_DEV_INTERACT__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__F2_CRCAP1_BUS_CONFIG__out_t F2_CRCAP1_BUS_CONFIG;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__F2_CRCAP2_DEV_INTERACT__out_t F2_CRCAP2_DEV_INTERACT;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RST_ACTION__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_TIME_PERIPHERAL__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_TIME_TARGET__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_DYNAMIC_ADDR__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RST_ACTION__out_t RST_ACTION;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_TIME_PERIPHERAL__out_t RESET_TIME_PERIPHERAL;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_TIME_TARGET__out_t RESET_TIME_TARGET;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__RESET_DYNAMIC_ADDR__out_t RESET_DYNAMIC_ADDR;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__out_t;

    typedef struct packed{
        logic [6:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_STATIC_ADDR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_STATIC_ADDR_VALID__out_t;

    typedef struct packed{
        logic [6:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_DYNAMIC_ADDR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_DYNAMIC_ADDR_VALID__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_STATIC_ADDR__out_t VIRT_STATIC_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_STATIC_ADDR_VALID__out_t VIRT_STATIC_ADDR_VALID;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_DYNAMIC_ADDR__out_t VIRT_DYNAMIC_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__VIRT_DYNAMIC_ADDR_VALID__out_t VIRT_DYNAMIC_ADDR_VALID;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__out_t;

    typedef struct packed{
        logic [15:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MWL__MWL__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MWL__MWL__out_t MWL;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MWL__out_t;

    typedef struct packed{
        logic [15:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__MRL__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__IBIL__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__MRL__out_t MRL;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__IBIL__out_t IBIL;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__EXTCAP_HEADER__out_t EXTCAP_HEADER;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CONTROL__out_t STBY_CR_CONTROL;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_ADDR__out_t STBY_CR_DEVICE_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CAPABILITIES__out_t STBY_CR_CAPABILITIES;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_CHAR__out_t STBY_CR_VIRTUAL_DEVICE_CHAR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_STATUS__out_t STBY_CR_STATUS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_CHAR__out_t STBY_CR_DEVICE_CHAR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_DEVICE_PID_LO__out_t STBY_CR_DEVICE_PID_LO;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_STATUS__out_t STBY_CR_INTR_STATUS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRTUAL_DEVICE_PID_LO__out_t STBY_CR_VIRTUAL_DEVICE_PID_LO;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_SIGNAL_ENABLE__out_t STBY_CR_INTR_SIGNAL_ENABLE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_INTR_FORCE__out_t STBY_CR_INTR_FORCE;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_GETCAPS__out_t STBY_CR_CCC_CONFIG_GETCAPS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_CCC_CONFIG_RSTACT_PARAMS__out_t STBY_CR_CCC_CONFIG_RSTACT_PARAMS;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_VIRT_DEVICE_ADDR__out_t STBY_CR_VIRT_DEVICE_ADDR;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MWL__out_t STBY_CR_MWL;
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__STBY_CR_MRL__out_t STBY_CR_MRL;
    } controller_I3CCSR__I3C_EC__StdbyCtrlMode__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__EXTCAP_HEADER__CAP_ID__out_t;

    typedef struct packed{
        logic [15:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__EXTCAP_HEADER__CAP_LENGTH__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__EXTCAP_HEADER__CAP_ID__out_t CAP_ID;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__EXTCAP_HEADER__CAP_LENGTH__out_t CAP_LENGTH;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__EXTCAP_HEADER__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_CONTROL__PLACEHOLDER__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_CONTROL__PLACEHOLDER__out_t PLACEHOLDER;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_CONTROL__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_STATUS__PLACEHOLDER__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_STATUS__PLACEHOLDER__out_t PLACEHOLDER;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_STATUS__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__REC_INTF_BYPASS__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__REC_PAYLOAD_DONE__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__REC_INTF_BYPASS__out_t REC_INTF_BYPASS;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__REC_PAYLOAD_DONE__out_t REC_PAYLOAD_DONE;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__out_t;

    typedef struct packed{
        logic [7:0] value;
        logic swmod;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__DEVICE_RESET_CTRL__out_t;

    typedef struct packed{
        logic [7:0] value;
        logic swmod;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__RECOVERY_CTRL_ACTIVATE_REC_IMG__out_t;

    typedef struct packed{
        logic [7:0] value;
        logic swmod;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__INDIRECT_FIFO_CTRL_RESET__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__DEVICE_RESET_CTRL__out_t DEVICE_RESET_CTRL;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__RECOVERY_CTRL_ACTIVATE_REC_IMG__out_t RECOVERY_CTRL_ACTIVATE_REC_IMG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__INDIRECT_FIFO_CTRL_RESET__out_t INDIRECT_FIFO_CTRL_RESET;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_RSVD_2__PLACEHOLDER__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_RSVD_2__PLACEHOLDER__out_t PLACEHOLDER;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_RSVD_2__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_RSVD_3__PLACEHOLDER__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_RSVD_3__PLACEHOLDER__out_t PLACEHOLDER;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_RSVD_3__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__INPUT_ENABLE__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__SCHMITT_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__KEEPER_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__PULL_DIR__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__PULL_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__IO_INVERSION__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__OD_EN__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__VIRTUAL_OD_EN__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__PAD_TYPE__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__INPUT_ENABLE__out_t INPUT_ENABLE;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__SCHMITT_EN__out_t SCHMITT_EN;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__KEEPER_EN__out_t KEEPER_EN;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__PULL_DIR__out_t PULL_DIR;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__PULL_EN__out_t PULL_EN;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__IO_INVERSION__out_t IO_INVERSION;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__OD_EN__out_t OD_EN;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__VIRTUAL_OD_EN__out_t VIRTUAL_OD_EN;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__PAD_TYPE__out_t PAD_TYPE;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_ATTR__DRIVE_SLEW_RATE__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_ATTR__DRIVE_STRENGTH__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_ATTR__DRIVE_SLEW_RATE__out_t DRIVE_SLEW_RATE;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_ATTR__DRIVE_STRENGTH__out_t DRIVE_STRENGTH;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_ATTR__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_FEATURE_2__PLACEHOLDER__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_FEATURE_2__PLACEHOLDER__out_t PLACEHOLDER;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_FEATURE_2__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_FEATURE_3__PLACEHOLDER__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_FEATURE_3__PLACEHOLDER__out_t PLACEHOLDER;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_FEATURE_3__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_R_REG__T_R__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_R_REG__T_R__out_t T_R;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_R_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_F_REG__T_F__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_F_REG__T_F__out_t T_F;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_F_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_DAT_REG__T_SU_DAT__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_DAT_REG__T_SU_DAT__out_t T_SU_DAT;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_DAT_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_DAT_I2C_REG__T_SU_DAT_I2C__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_DAT_I2C_REG__T_SU_DAT_I2C__out_t T_SU_DAT_I2C;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_DAT_I2C_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_DAT_REG__T_HD_DAT__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_DAT_REG__T_HD_DAT__out_t T_HD_DAT;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_DAT_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_REG__T_HIGH__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_REG__T_HIGH__out_t T_HIGH;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_OD_REG__T_HIGH_OD__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_OD_REG__T_HIGH_OD__out_t T_HIGH_OD;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_OD_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_INIT_OD_REG__T_HIGH_INIT_OD__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_INIT_OD_REG__T_HIGH_INIT_OD__out_t T_HIGH_INIT_OD;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_INIT_OD_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_I2C_REG__T_HIGH_I2C__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_I2C_REG__T_HIGH_I2C__out_t T_HIGH_I2C;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_I2C_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_REG__T_LOW__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_REG__T_LOW__out_t T_LOW;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_OD_REG__T_LOW_OD__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_OD_REG__T_LOW_OD__out_t T_LOW_OD;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_OD_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_I2C_REG__T_LOW_I2C__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_I2C_REG__T_LOW_I2C__out_t T_LOW_I2C;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_I2C_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_STA_REG__T_HD_STA__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_STA_REG__T_HD_STA__out_t T_HD_STA;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_STA_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_STA_I2C_REG__T_HD_STA_I2C__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_STA_I2C_REG__T_HD_STA_I2C__out_t T_HD_STA_I2C;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_STA_I2C_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_RSTA_REG__T_HD_RSTA__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_RSTA_REG__T_HD_RSTA__out_t T_HD_RSTA;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_RSTA_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STA_REG__T_SU_STA__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STA_REG__T_SU_STA__out_t T_SU_STA;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STA_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STA_I2C_REG__T_SU_STA_I2C__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STA_I2C_REG__T_SU_STA_I2C__out_t T_SU_STA_I2C;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STA_I2C_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STO_REG__T_SU_STO__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STO_REG__T_SU_STO__out_t T_SU_STO;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STO_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STO_I2C_REG__T_SU_STO_I2C__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STO_I2C_REG__T_SU_STO_I2C__out_t T_SU_STO_I2C;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STO_I2C_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_DS_OD_REG__T_DS_OD__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_DS_OD_REG__T_DS_OD__out_t T_DS_OD;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_DS_OD_REG__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_FREE_REG__T_FREE__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_FREE_REG__T_FREE__out_t T_FREE;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_FREE_REG__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_FREE_I2C_REG__T_FREE_I2C__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_FREE_I2C_REG__T_FREE_I2C__out_t T_FREE_I2C;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_FREE_I2C_REG__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_AVAL_REG__T_AVAL__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_AVAL_REG__T_AVAL__out_t T_AVAL;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_AVAL_REG__out_t;

    typedef struct packed{
        logic [31:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_IDLE_REG__T_IDLE__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_IDLE_REG__T_IDLE__out_t T_IDLE;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_IDLE_REG__out_t;

    typedef struct packed{
        logic value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__HDR_TIMEOUT_EN_REG__HDR_TIMEOUT_EN__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__HDR_TIMEOUT_EN_REG__HDR_TIMEOUT_EN__out_t HDR_TIMEOUT_EN;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__HDR_TIMEOUT_EN_REG__out_t;

    typedef struct packed{
        logic [19:0] value;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HDR_TIMEOUT_REG__T_HDR_TIMEOUT__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HDR_TIMEOUT_REG__T_HDR_TIMEOUT__out_t T_HDR_TIMEOUT;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HDR_TIMEOUT_REG__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__SoCMgmtIf__EXTCAP_HEADER__out_t EXTCAP_HEADER;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_CONTROL__out_t SOC_MGMT_CONTROL;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_STATUS__out_t SOC_MGMT_STATUS;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_CFG__out_t REC_INTF_CFG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__REC_INTF_REG_W1C_ACCESS__out_t REC_INTF_REG_W1C_ACCESS;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_RSVD_2__out_t SOC_MGMT_RSVD_2;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_RSVD_3__out_t SOC_MGMT_RSVD_3;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_CONF__out_t SOC_PAD_CONF;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_PAD_ATTR__out_t SOC_PAD_ATTR;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_FEATURE_2__out_t SOC_MGMT_FEATURE_2;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__SOC_MGMT_FEATURE_3__out_t SOC_MGMT_FEATURE_3;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_R_REG__out_t T_R_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_F_REG__out_t T_F_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_DAT_REG__out_t T_SU_DAT_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_DAT_I2C_REG__out_t T_SU_DAT_I2C_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_DAT_REG__out_t T_HD_DAT_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_REG__out_t T_HIGH_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_OD_REG__out_t T_HIGH_OD_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_INIT_OD_REG__out_t T_HIGH_INIT_OD_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HIGH_I2C_REG__out_t T_HIGH_I2C_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_REG__out_t T_LOW_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_OD_REG__out_t T_LOW_OD_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_LOW_I2C_REG__out_t T_LOW_I2C_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_STA_REG__out_t T_HD_STA_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_STA_I2C_REG__out_t T_HD_STA_I2C_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HD_RSTA_REG__out_t T_HD_RSTA_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STA_REG__out_t T_SU_STA_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STA_I2C_REG__out_t T_SU_STA_I2C_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STO_REG__out_t T_SU_STO_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_SU_STO_I2C_REG__out_t T_SU_STO_I2C_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_DS_OD_REG__out_t T_DS_OD_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_FREE_REG__out_t T_FREE_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_FREE_I2C_REG__out_t T_FREE_I2C_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_AVAL_REG__out_t T_AVAL_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_IDLE_REG__out_t T_IDLE_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__HDR_TIMEOUT_EN_REG__out_t HDR_TIMEOUT_EN_REG;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__T_HDR_TIMEOUT_REG__out_t T_HDR_TIMEOUT_REG;
    } controller_I3CCSR__I3C_EC__SoCMgmtIf__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__CtrlCfg__EXTCAP_HEADER__CAP_ID__out_t;

    typedef struct packed{
        logic [15:0] value;
    } controller_I3CCSR__I3C_EC__CtrlCfg__EXTCAP_HEADER__CAP_LENGTH__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__CtrlCfg__EXTCAP_HEADER__CAP_ID__out_t CAP_ID;
        controller_I3CCSR__I3C_EC__CtrlCfg__EXTCAP_HEADER__CAP_LENGTH__out_t CAP_LENGTH;
    } controller_I3CCSR__I3C_EC__CtrlCfg__EXTCAP_HEADER__out_t;

    typedef struct packed{
        logic [1:0] value;
    } controller_I3CCSR__I3C_EC__CtrlCfg__CONTROLLER_CONFIG__OPERATION_MODE__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__CtrlCfg__CONTROLLER_CONFIG__OPERATION_MODE__out_t OPERATION_MODE;
    } controller_I3CCSR__I3C_EC__CtrlCfg__CONTROLLER_CONFIG__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__CtrlCfg__EXTCAP_HEADER__out_t EXTCAP_HEADER;
        controller_I3CCSR__I3C_EC__CtrlCfg__CONTROLLER_CONFIG__out_t CONTROLLER_CONFIG;
    } controller_I3CCSR__I3C_EC__CtrlCfg__out_t;

    typedef struct packed{
        logic [7:0] value;
    } controller_I3CCSR__I3C_EC__TERMINATION_EXTCAP_HEADER__CAP_ID__out_t;

    typedef struct packed{
        logic [15:0] value;
    } controller_I3CCSR__I3C_EC__TERMINATION_EXTCAP_HEADER__CAP_LENGTH__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__TERMINATION_EXTCAP_HEADER__CAP_ID__out_t CAP_ID;
        controller_I3CCSR__I3C_EC__TERMINATION_EXTCAP_HEADER__CAP_LENGTH__out_t CAP_LENGTH;
    } controller_I3CCSR__I3C_EC__TERMINATION_EXTCAP_HEADER__out_t;

    typedef struct packed{
        controller_I3CCSR__I3C_EC__StdbyCtrlMode__out_t StdbyCtrlMode;
        controller_I3CCSR__I3C_EC__SoCMgmtIf__out_t SoCMgmtIf;
        controller_I3CCSR__I3C_EC__CtrlCfg__out_t CtrlCfg;
        controller_I3CCSR__I3C_EC__TERMINATION_EXTCAP_HEADER__out_t TERMINATION_EXTCAP_HEADER;
    } controller_I3CCSR__I3C_EC__out_t;

    typedef struct packed{
        logic req;
        logic [9:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } controller_I3CCSR__DAT__out_t;

    typedef struct packed{
        logic req;
        logic [10:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } controller_I3CCSR__DCT__out_t;

    typedef struct packed{
        controller_I3CCSR__I3CBase__out_t I3CBase;
        controller_I3CCSR__PIOControl__out_t PIOControl;
        controller_I3CCSR__I3C_EC__out_t I3C_EC;
        controller_I3CCSR__DAT__out_t DAT;
        controller_I3CCSR__DCT__out_t DCT;
    } controller_I3CCSR__out_t;
endpackage
